### PR TITLE
Added material to angular

### PR DESCRIPTION
**Pull request by GUIMess**
# Description
DO NOT AUTO APPROVE
added pink/green material.  Tested with a slider on render. Prettier auto formatted frontend/src/app/app.module.ts.  Left Package-lock in for CI/CD practices. Unsure of other testing to be done or structure I should've followed. All input begged for. Tear it up please.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [ ] Unit test

# Checklist:
- [x] I have pulled code from main and re-tested changes before opening the PR
- [x] No new bugs or vulnerabilities have been found in the code
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

image

### CODE REVIEW

**Review by bob-fornal — APPROVED** [review]

**Comment by GUIMess** [comment]
[HTTAT-7 - Material UI](https://trello.com/c/ue7jccJo/7-httat-7-material-ui)

**Comment by GUIMess** [comment]
image

seems like it may be an issue 😳

**Comment by bob-fornal** [comment]
We'll figure that out. Keep the URL you used to install material and we'll find the missing steps next meeting.

**Comment by thecornisians** [comment]
LGTM

**Review by dhess268 — COMMENTED** [review]
Nice work!

**Review by meghannfh — APPROVED** [review]
Looks good!

**Review by dhess268 — APPROVED** [review]

**Comment by CloudCoded** [comment]
This looks good

**Pull request merged**
