### PR TITLE
feature/HTTAT-1 Install Angular

### PR DESCRIPTION
**Pull request by bob-fornal**
# Work Completed

- Setup Angular 15 (in frontend folder)
- Basic cleanup
- Talk through Angular
- Configure the folders (structure)
- Setup Unit Test (ChromeHeadless/watch off)

### CODE REVIEW

**Review by mohamed-hassan93 — APPROVED** [review]

**Review by GUIMess — APPROVED** [review]
I guess it's ok

**Review by timtom619 — APPROVED** [review]
Looks good!

**Review by bellsofaba — APPROVED** [review]

**Comment by bob-fornal** [comment]
[HTTAT-1 - Install Angular 15](https://trello.com/c/764PqzJh/1-httat-1-install-angular-15)

**Comment by CloudCoded** [comment]
it's amazing so far

**Review by cynthiablack — COMMENTED** [review]
No conflicts detected, PR merged - no issue from me.

**Comment by SachiGoto** [comment]
Great!

**Pull request merged**
