### PR TITLE
Create PR Template

### PR DESCRIPTION
**Pull request by bob-fornal**
# Description
PR Template Added.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [ ] Unit test

# Checklist:
- [x] I have pulled code from main and re-tested changes before opening the PR
- [x] No new bugs or vulnerabilities have been found in the code
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by GUIMess — APPROVED** [review]
This is a great template and we'll get a bunch of use from it.

**Review by meghannfh — APPROVED** [review]
looks good!

**Review by jessicafuller808 — APPROVED** [review]

**Review by mohamed-hassan93 — APPROVED** [review]
Looks good!

**Comment by bellsofaba** [comment]
Good to go!

**Comment by bellsofaba** [comment]
Good to go!

**Comment by Bishama** [comment]
Looks good.

**Review by Bishama — COMMENTED** [review]
Looks good.

**Review by bellsofaba — COMMENTED** [review]
Looks great.

**Pull request merged**
