### PR TITLE
Favicon

### PR DESCRIPTION
**Pull request by katiehom**
Add favicon

# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [ ] Unit test

# Checklist:
- [ ] I have pulled code from main and re-tested changes before opening the PR
- [ ] No new bugs or vulnerabilities have been found in the code
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by katiehom** [comment]
I will also try creating the favicon using Adobe Illustrator to see if we can keep any more precision in the image by sizing it down in that program.

**Comment by bob-fornal** [comment]
It looks like it's got a black background ... transparency?

**Comment by katiehom** [comment]
Yes, when I was converting the transparent image it gets distorted because it's not a square. I added the black background to give it a square shape. I will see if using Illustrator allows me to create a canvas that allows me to keep the image its intended shape and size, but allows for a square shape overall with transparency.

**Comment by katiehom** [comment]
favicon-httat

Here is the logo scaled down to 32px using Cloudinary.

**Pull request closed without merging**
